name: CC Quotation Workflow
on:
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
  # uses: QAInsights/PerfAction@5a3c503bff845dd019d4b6e30d71f4585494a2ea
        uses: QAInsights/PerfAction@v5.6.2
        with:
    # jmeter test plan to execute
          test-plan-path: './Perf_test_UAT_CC-Integration_QuotationWorkflow.jmx'
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results_${{ env.NOW }}
          path: |
              dashboard/
              testresults.jtl
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports_${{ env.NOW }}
          path: reports
