name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: PerfAction for JMeter
  # You may pin to the exact commit or the version.
  # uses: QAInsights/PerfAction@2c22274f313e13ce9ddaf60c9f337a0e628fcb9d
        uses: QAInsights/PerfAction@2.0
        with:
    # jmeter test plan to execute
          test-plan-path: './Quotation_Overflow.jmx'
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
